# .github/workflows/docker.yml
name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t farjadalam326/docker:latest .

      - name: Push Docker image
        run: docker push farjadalam326/docker:latest

# deploy:
#     runs-on: ubuntu-latest
#     needs: docker
#     steps:
#       - name: Deploy to Server via SSH
#         uses: appleboy/ssh-action@v1.0.3
#         with:
#           host: ${{ secrets.SERVER_HOST }}
#           username: ${{ secrets.SERVER_USER }}
#           key: ${{ secrets.SERVER_SSH_KEY }}
#           script: |
#             docker pull yasin885/todo:latest
#             docker stop todo || true
#             docker rm todo || true
#             docker run -d -p 80:80 --name todo yasin885/todo:latest
 